version: 2
updates:
  # Go module dependencies.
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  # GitHub Actions used in workflows.
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5
