package client

// art.go — pixel-art renderer and menu art for the Loba start-menu screen.
//
// Rendering techniques:
//   - Half-block (▀/▄): each terminal row encodes two pixel rows.
//   - Braille (⠁–⣿): each terminal cell encodes a 2×4 pixel block.
//
// LOBA wordmark: hand-crafted pixel grid, 10 px tall (5 terminal rows via
// half-block), sunset gradient per row (magenta→pink→orange).
//
// Hot dog logo: half-block sprite, 24 px wide × 24 px tall (12 terminal rows).
// Generated by tools/png2sprite; braille technique is preserved in RenderBrailleSprite
// for future line-art use.

import (
	"strings"

	"github.com/charmbracelet/lipgloss"

	"github.com/zwenger/TUI-LOBA/internal/protocol"
)

// ─── Palette ──────────────────────────────────────────────────────────────────

// hotDogPalette maps a single rune to a 256-colour terminal code.
// '.' and ' ' are reserved for transparent pixels.
//
// Generated by tools/png2sprite from a reference image (not committed).
// Command: go run ./tools/png2sprite -n <reference.png> -width 24 -colors 12 -bg-tolerance 30 -out go -name hotDog -style halfblock
var hotDogPalette = map[rune]string{
	'A': "95",  // muted mauve / shadow blend  — approx RGB(135,95,95)
	'B': "124", // medium red / sausage core   — approx RGB(175,0,0)
	'C': "131", // warm mauve / sausage edge   — approx RGB(175,95,95)
	'D': "166", // orange-red / sausage bright — approx RGB(215,95,0)
	'E': "173", // sandy orange / bun edge     — approx RGB(215,135,95)
	'F': "179", // golden / bun transition     — approx RGB(215,175,95)
	'G': "214", // gold-orange / bun body      — approx RGB(255,175,0)
	'H': "220", // bright yellow / mustard     — approx RGB(255,215,0)
	'I': "221", // pale yellow / bun highlight — approx RGB(255,215,95)
	'J': "236", // dark charcoal / outline     — approx RGB(48,48,48)
	'K': "238", // mid charcoal / soft outline — approx RGB(68,68,68)
}

// ─── Sprite definition ────────────────────────────────────────────────────────

// hotDogSprite is a 24-wide × 24-tall pixel grid encoded as rune rows.
// Each rune maps to hotDogPalette; '.' = transparent.
// Renders as 12 terminal rows via half-block encoding.
//
// Generated by tools/png2sprite from a reference image (not committed).
// Command: go run ./tools/png2sprite -n <reference.png> -width 24 -colors 12 -bg-tolerance 30 -out go -name hotDog -style halfblock
var hotDogSprite = []string{
	"....JKKKK...............",
	"...KKBDDDBA.............",
	"..AEEBDEEDFA............",
	".AHHIEDDEDEA............",
	".GHHHIBDEDDFJ...........",
	"AHHHHIBEEDDFK...........",
	"AHHHHIBBDFEEA...........",
	"AHHHHIBBDEDEA...........",
	"AGHHHHEBDIFDEK..........",
	"AGHHHHEBBDDIFK..........",
	"AGHHHHFBBDDFEC..........",
	"JGHHHHICBDFEDEK.........",
	".EGHHHHFBDEEFFC.........",
	".AGHHHHIBBBDEEEC........",
	"..EHHHHHICBBDEFICAJ.....",
	"..AGHHHHHIEBBBDFGFFCA...",
	"...CHHHHHHHIEBBDDEFDECK.",
	"...AGHHHHHHHIIFEBBFFDDCK",
	"....AGHHHHHHHHIIIFBDDBBA",
	".....AGGHHHHHHHHHIEBBBBA",
	"......ACGGHHHHHHHHCBBBDA",
	".......KACGGGHHHHHGDDECK",
	"..........KACGGGGGGGGCK.",
	".............JJAAAAAJ...",
}

// ─── Style cache ──────────────────────────────────────────────────────────────

// styleKey encodes a (fg, bg) colour pair; "" means transparent / no colour set.
type styleKey struct{ fg, bg string }

// styleCache caches lipgloss styles by colour pair so we don't allocate on
// every pixel during rendering.
var styleCache = map[styleKey]lipgloss.Style{}

func pixelStyle(fg, bg string) lipgloss.Style {
	k := styleKey{fg, bg}
	if s, ok := styleCache[k]; ok {
		return s
	}
	s := lipgloss.NewStyle()
	if fg != "" {
		s = s.Foreground(lipgloss.Color(fg))
	}
	if bg != "" {
		s = s.Background(lipgloss.Color(bg))
	}
	styleCache[k] = s
	return s
}

// ─── Half-block renderer ──────────────────────────────────────────────────────

// RenderSprite converts a pixel grid + palette into a half-block terminal string.
//
// The sprite grid is a []string where each string is one pixel row and each rune
// maps to the palette (or is '.' / ' ' for transparent).
//
// Half-block encoding per column:
//
//	top & bottom coloured  → '▀'  fg=top   bg=bottom
//	top only               → '▀'  fg=top   bg=none
//	bottom only            → '▄'  fg=bottom bg=none
//	both transparent       → ' '
//
// Output lines are guaranteed to be equal lipgloss.Width so they compose cleanly
// with JoinHorizontal / centering.
func RenderSprite(grid []string, palette map[rune]string) string {
	if len(grid) == 0 {
		return ""
	}

	// Pad grid to even number of rows.
	rows := grid
	if len(rows)%2 != 0 {
		rows = append(rows, "")
	}

	// Determine maximum column count.
	maxCols := 0
	for _, row := range rows {
		c := len([]rune(row))
		if c > maxCols {
			maxCols = c
		}
	}

	var lines []string
	for r := 0; r < len(rows); r += 2 {
		topRunes := []rune(rows[r])
		botRunes := []rune(rows[r+1])

		var sb strings.Builder
		for c := 0; c < maxCols; c++ {
			topRune, botRune := '.', '.'
			if c < len(topRunes) {
				topRune = topRunes[c]
			}
			if c < len(botRunes) {
				botRune = botRunes[c]
			}

			topColor := palette[topRune] // "" if transparent
			botColor := palette[botRune] // "" if transparent

			switch {
			case topColor != "" && botColor != "":
				sb.WriteString(pixelStyle(topColor, botColor).Render("▀"))
			case topColor != "":
				sb.WriteString(pixelStyle(topColor, "").Render("▀"))
			case botColor != "":
				sb.WriteString(pixelStyle(botColor, "").Render("▄"))
			default:
				sb.WriteString(" ")
			}
		}
		lines = append(lines, sb.String())
	}

	return strings.Join(lines, "\n")
}

// ─── Braille renderer ─────────────────────────────────────────────────────────

// brailleBitMap encodes which bit in the braille Unicode offset each of the
// 8 pixel positions (row 0-3, col 0-1) maps to.
//
// Standard braille bit layout (Unicode U+2800+offset):
//   bit 0 = dot 1 = row0,col0   bit 3 = dot 4 = row0,col1
//   bit 1 = dot 2 = row1,col0   bit 4 = dot 5 = row1,col1
//   bit 2 = dot 3 = row2,col0   bit 5 = dot 6 = row2,col1
//   bit 6 = dot 7 = row3,col0   bit 7 = dot 8 = row3,col1
//
// Full cell (all 8 dots set) = U+28FF = ⣿
var brailleBitMap = [4][2]uint8{
	{0, 3}, // row 0: col0=bit0, col1=bit3
	{1, 4}, // row 1: col0=bit1, col1=bit4
	{2, 5}, // row 2: col0=bit2, col1=bit5
	{6, 7}, // row 3: col0=bit6, col1=bit7
}

// RenderBrailleSprite composes a braille-encoded terminal string from:
//   - dots:       pixel-row mask strings ('#'=on, '.'=off), width W pixels, height H pixels
//                 W must be even (2 px per cell column), H must be multiple of 4 (4 px per cell row)
//   - cellColors: cell-row color strings, width=W/2, height=H/4; rune maps to palette; '.'=transparent
//   - palette:    map[rune]string of xterm-256 codes for cell colors
//
// Each 2×4 pixel block becomes one braille character (U+2800+offset), colored
// with the cell's palette entry via cached lipgloss styles.
// Transparent cells (no opaque pixels) render as a space.
// Output lines are all equal lipgloss.Width for clean composition.
func RenderBrailleSprite(dots []string, cellColors []string, palette map[rune]string) string {
	if len(dots) == 0 || len(cellColors) == 0 {
		return ""
	}

	pixH := len(dots)
	pixW := 0
	if pixH > 0 {
		pixW = len([]rune(dots[0]))
	}
	if pixW == 0 {
		return ""
	}

	cellCols := pixW / 2
	cellRows := pixH / 4

	var lines []string

	for cy := 0; cy < cellRows; cy++ {
		var sb strings.Builder
		cellRowStr := []rune{}
		if cy < len(cellColors) {
			cellRowStr = []rune(cellColors[cy])
		}

		for cx := 0; cx < cellCols; cx++ {
			// Determine braille rune offset from 8 dot positions.
			var offset uint8
			for dy := 0; dy < 4; dy++ {
				for dx := 0; dx < 2; dx++ {
					py := cy*4 + dy
					px := cx*2 + dx
					if py < len(dots) {
						row := dots[py]
						if px < len(row) && row[px] == '#' {
							bit := brailleBitMap[dy][dx]
							offset |= 1 << bit
						}
					}
				}
			}

			// Look up cell color.
			var colorCode string
			if cx < len(cellRowStr) {
				r := cellRowStr[cx]
				if r != '.' {
					colorCode = palette[r]
				}
			}

			if offset == 0 || colorCode == "" {
				// No dots or transparent — emit space.
				sb.WriteString(" ")
			} else {
				ch := string(rune(0x2800 + int(offset)))
				sb.WriteString(pixelStyle(colorCode, "").Render(ch))
			}
		}
		lines = append(lines, sb.String())
	}

	return strings.Join(lines, "\n")
}

// renderHotDog returns the fully-coloured hot dog sprite string using the
// half-block renderer.  Renders as 12 terminal rows × 24 terminal columns.
func renderHotDog() string {
	return RenderSprite(hotDogSprite, hotDogPalette)
}

// ─── LOBA wordmark ────────────────────────────────────────────────────────────

// lobaWordmarkGrid is a hand-crafted 10-pixel-tall pixel mask for the four
// letters L O B A, separated by 2px gaps.
//
// Letterforms (2px stroke throughout, 10px tall):
//   L (cols  0- 5, 6px): vertical bar, foot on rows 8-9
//   O (cols  8-15, 8px): rounded box — top/bottom edges inset 1px
//   B (cols 18-25, 8px): spine + two bowls (rows 0-4 and 4-9), closed bottom
//   A (cols 28-35, 8px): rounded peak, full crossbar on row 4, legs to baseline
// Total width: 36 px → renders as 5 terminal rows × 36 cols via half-blocks.
//
// '#' = filled pixel, '.' = empty (transparent). Every row exactly 36 chars.
// Visual self-check: go test -v -run TestWordmarkVisualMask
var lobaWordmarkGrid = []string{
	// col: 000000000111111111122222222223333333
	//      012345678901234567890123456789012345
	/* r0 */ "##.......######...#######....######.",
	/* r1 */ "##......##....##..##....##..##....##",
	/* r2 */ "##......##....##..##....##..##....##",
	/* r3 */ "##......##....##..##....##..##....##",
	/* r4 */ "##......##....##..#######...########",
	/* r5 */ "##......##....##..##....##..##....##",
	/* r6 */ "##......##....##..##....##..##....##",
	/* r7 */ "##......##....##..##....##..##....##",
	/* r8 */ "######..##....##..##....##..##....##",
	/* r9 */ "######...######...#######...##....##",
}

// lobaWordmarkColors defines the gradient per pixel row.
// Rows 0–1: magenta (201), 2–3: hot-pink (213), 4–5: pink (212),
// 6–7: light orange (209), 8–9: amber (214).
var lobaWordmarkColors = [10]string{
	"201", // row 0 — deep magenta
	"201", // row 1
	"213", // row 2 — hot pink
	"213", // row 3
	"212", // row 4 — pink
	"212", // row 5
	"209", // row 6 — salmon/orange-pink
	"209", // row 7
	"214", // row 8 — amber
	"214", // row 9
}

// renderWordmarkRow returns a single half-block terminal line for two pixel
// rows (top=rowIdx, bottom=rowIdx+1) of the wordmark.
// Each '#' pixel uses the gradient color for its row.
func renderWordmarkRow(topRow, botRow int) string {
	top := []rune(lobaWordmarkGrid[topRow])
	bot := []rune(lobaWordmarkGrid[botRow])
	topColor := lobaWordmarkColors[topRow]
	botColor := lobaWordmarkColors[botRow]

	maxCols := len(top)
	if len(bot) > maxCols {
		maxCols = len(bot)
	}

	var sb strings.Builder
	for c := 0; c < maxCols; c++ {
		topPx, botPx := '.', '.'
		if c < len(top) {
			topPx = top[c]
		}
		if c < len(bot) {
			botPx = bot[c]
		}

		topFilled := topPx == '#'
		botFilled := botPx == '#'

		switch {
		case topFilled && botFilled:
			sb.WriteString(pixelStyle(topColor, botColor).Render("▀"))
		case topFilled:
			sb.WriteString(pixelStyle(topColor, "").Render("▀"))
		case botFilled:
			sb.WriteString(pixelStyle(botColor, "").Render("▄"))
		default:
			sb.WriteString(" ")
		}
	}
	return sb.String()
}

// renderLobaWordmark returns the LOBA logo as a 5-line half-block string with
// a magenta→pink→orange gradient. Each pair of pixel rows becomes one terminal row.
func renderLobaWordmark() string {
	lines := make([]string, 5)
	for i := 0; i < 5; i++ {
		lines[i] = renderWordmarkRow(i*2, i*2+1)
	}
	return strings.Join(lines, "\n")
}

// ─── Card fan footer ──────────────────────────────────────────────────────────

// menuFanCards are the fixed cards shown in the start-menu fan.
var menuFanCards = []protocol.CardView{
	{Rank: 1, Suit: 0},  // A♠
	{Rank: 13, Suit: 1}, // K♥
	{Rank: 12, Suit: 2}, // Q♦
	{Rank: 11, Suit: 3}, // J♣
	{Rank: 0, Suit: -1}, // joker
}

// cardFanBlank is an 8×5 empty block matching one fan slot so that undealt
// slots keep the panel size stable during the deal animation.
const cardFanBlank = "        \n        \n        \n        \n        "

// padCardSlot places a 7-wide card box inside an 8-wide slot. The spare column
// normally trails the card; during a shake's odd ticks it leads instead, moving
// the card one column right without disturbing its neighbours.
func padCardSlot(box string, shifted bool) string {
	lines := strings.Split(box, "\n")
	for i, ln := range lines {
		if shifted {
			lines[i] = " " + ln
		} else {
			lines[i] = ln + " "
		}
	}
	return strings.Join(lines, "\n")
}

// cardFanFooter renders the menu card-fan using the same full card boxes as the
// player's hand (renderCardBox). dealt is the number of deal-animation ticks
// elapsed: each tick deals one card face-down and the following tick flips it
// face-up; values at or above menuDealSteps render the full resting fan.
// shakeCard (when >= 0) wiggles that card one column on odd shakeTicks.
func cardFanFooter(dealt, shakeCard, shakeTicks int) string {
	blocks := make([]string, len(menuFanCards))
	for i, c := range menuFanCards {
		switch {
		case i >= dealt: // not dealt yet
			blocks[i] = cardFanBlank
			continue
		case i == dealt-1 && dealt < menuDealSteps: // just dealt — face down
			c.Hidden = true
		}
		shifted := i == shakeCard && shakeTicks%2 == 1
		blocks[i] = padCardSlot(renderCardBox(c, false, false), shifted)
	}
	return lipgloss.JoinHorizontal(lipgloss.Top, blocks...)
}
